export const ACHIEVEMENT_BY_MODULE_TITLE = {
  'Entendendo o Dinheiro': ['primeiro_passo'],
  'Poupança': ['guardador_de_dinheiro'],
  'Planejamento': ['mestre_planejamento'],
  'Consumo Consciente': ['consumo_consciente'],
  'Meu Primeiro Pequeno Negócio': ['grande_ideia', 'jovem_empreendedor'],
  'Divulgação': ['mestre_divulgacao'],
  'Precificação': ['especialista_precos'],
  'Atendimento ao Cliente': ['atendimento_nota_10'],
  'Quem sou eu?': ['explorador_de_si_mesmo'],
  'Confiança em mim mesmo': ['confiante'],
  'Disciplina e Hábitos': ['disciplinado'],
  'Organização do Meu Dia': ['organizador'],
  'Objetivos e Metas': ['mestre_das_metas'],
  'Responsabilidade': ['responsavel_nota_10'],
  'Persistência: Aprendendo com os Erros': ['persistente'],
  'Mentalidade de Crescimento': ['mente_em_crescimento'],
  'O que é um computador?': ['explorador_digital'],
  'Organização Digital': ['organizador_de_arquivos'],
  'Navegando na Internet': ['navegador_seguro'],
  'E-mail: Minha Caixa de Mensagens': ['mensageiro_digital'],
  'Criando Documentos de Texto': ['criador_de_documentos'],
  'Apresentações: Contando Ideias em Slides': ['apresentador'],
  'Planilhas: Organizando Números': ['planilheiro'],
  'Digitação e Atalhos': ['digitador_rapido'],
  'Senhas Fortes e Seguras': ['mestre_das_senhas'],
  'Privacidade: O Que é Meu, é Meu': ['guardiao_da_privacidade'],
  'Golpes e Links Suspeitos': ['detetive_de_golpes'],
  'Desconhecidos na Internet': ['alerta_ligado'],
  'Fotos, Vídeos e Localização': ['cuidadoso_com_imagens'],
  'Cyberbullying: Respeito Também Online': ['gentileza_online'],
  'Fake News: Nem Tudo que Circula é Verdade': ['verificador_de_fatos'],
  'Tempo de Tela e Uso Responsável': ['equilibrio_digital'],
  'O que é Inteligência Artificial?': ['explorador_de_ia'],
  'Onde Encontro IA no Meu Dia a Dia': ['cacador_de_ia'],
  'Como Conversar Bem com uma IA': ['comunicador_com_ia'],
  'IA que Cria: Textos e Imagens': ['criador_com_ia'],
  'A IA Pode Errar: Verificando Informações': ['checador_de_ia'],
  'Criatividade com IA: Inventando Histórias': ['contador_de_historias_ia'],
  'Recomendações: Como a IA Sugere Coisas pra Mim': ['curioso_das_recomendacoes'],
  'Usando IA com Responsabilidade e Segurança': ['ia_com_responsabilidade'],
  'O que é Programação?': ['programador_iniciante'],
  'Algoritmos: A Receita que o Computador Segue': ['mestre_dos_algoritmos'],
  'Sequência e Instruções': ['organizador_de_instrucoes'],
  'Condições: Se Isso, Então Aquilo': ['mestre_das_condicoes'],
  'Repetições: Fazendo a Mesma Coisa Várias Vezes': ['mestre_das_repeticoes'],
  'Variáveis: Guardando Informações': ['guardiao_de_variaveis'],
  'Eventos: Quando Algo Acontece': ['cacador_de_eventos'],
  'Lógica de Jogos: Planejando Meu Primeiro Jogo': ['planejador_de_jogos'],
  'O que é Criatividade?': ['mente_criativa'],
  'Cores: A Linguagem Silenciosa': ['mestre_das_cores'],
  'Formas e Composição': ['arquiteto_de_formas'],
  'Contraste: Fazendo Coisas se Destacarem': ['mestre_do_contraste'],
  'Tipografia: A Voz das Letras': ['tipografo'],
  'Desenho: Ideias que Ganham Forma': ['desenhista'],
  'Identidade Visual e Logotipo': ['criador_de_marca'],
  'Criando um Cartaz': ['cartazista'],
  'Storytelling: Contando Histórias que Prendem Atenção': ['mestre_do_storytelling'],
  'Roteiro: Planejando Antes de Gravar': ['roteirista'],
  'Enquadramento e Fotografia': ['fotografo_iniciante'],
  'Áudio: O Som Também Conta a História': ['engenheiro_de_som'],
  'Edição Básica: Dando Ritmo ao Conteúdo': ['editor_de_video'],
  'Thumbnail e Legenda: A Primeira Impressão': ['mestre_da_thumbnail'],
  'Direitos Autorais e Uso Responsável de Imagens': ['respeitador_de_direitos'],
  'Publicando com Segurança': ['publicador_seguro'],
  'Respeito e Empatia': ['respeitoso'],
  'Direitos e Deveres': ['conhecedor_de_direitos'],
  'Regras: Por que Existem?': ['seguidor_consciente'],
  'Cooperação: Trabalhando Juntos': ['cooperador'],
  'Diversidade de Opiniões': ['mente_aberta'],
  'Resolução de Conflitos': ['pacificador'],
  'Vivendo em Comunidade': ['vizinho_exemplar'],
  'Identificando Problemas e Propondo Soluções': ['agente_de_mudanca'],
}

export const TOTAL_MODULES = 12
export const FINAL_ACHIEVEMENT_CODE = 'pequeno_empreendedor'

export const FINAL_ACHIEVEMENT_BY_COURSE_SLUG = {
  'educacao-financeira-empreendedorismo': 'pequeno_empreendedor',
  'inteligencia-desenvolvimento-pessoal': 'explorador_da_evolucao',
  'informatica-do-zero': 'mestre_da_informatica',
  'seguranca-na-internet': 'guardiao_digital',
  'inteligencia-artificial-para-criancas': 'jovem_especialista_ia',
  'programacao-para-criancas': 'pequeno_programador',
  'criatividade-e-design': 'designer_criativo',
  'criacao-de-conteudo-digital': 'criador_de_conteudo',
  'cidadania-e-vida-em-sociedade': 'cidadao_consciente',
}
