// Cada curso tem um projeto final com campos diferentes, mas reaproveitam as
// mesmas colunas da tabela student_projects (que é genérica o suficiente).
export const PROJECT_TEMPLATES = {
  'educacao-financeira-empreendedorismo': {
    emoji: '🚀',
    title: 'Projeto Final: Meu Primeiro Negócio',
    subtitle: 'Você aprendeu, praticou e planejou. Agora é hora de criar!',
    showProfitCalc: true,
    submitLabel: 'Concluir curso e gerar certificado 🎓',
    fields: [
      { db: 'business_name', label: 'Nome do negócio', type: 'text', placeholder: 'Ex: Doces da Ana' },
      { db: 'product_service', label: 'Produto ou serviço', type: 'text', placeholder: 'O que você vai oferecer?' },
      { db: 'target_audience', label: 'Público-alvo', type: 'text', placeholder: 'Quem vai comprar de você?' },
      { db: 'problem_solved', label: 'Qual problema ele resolve', type: 'textarea', placeholder: 'Que necessidade ou desejo isso atende?' },
      { db: 'cost', label: 'Custo (R$)', type: 'number', placeholder: '0.00' },
      { db: 'sale_price', label: 'Preço de venda (R$)', type: 'number', placeholder: '0.00' },
      { db: 'marketing_strategy', label: 'Estratégia de divulgação', type: 'textarea', placeholder: 'Como as pessoas vão saber do seu negócio?' },
      { db: 'service_approach', label: 'Forma de atendimento', type: 'textarea', placeholder: 'Como você vai tratar seus clientes?' },
      { db: 'social_post_text', label: 'Publicação para rede social (fictícia)', type: 'textarea', placeholder: 'Escreva um post de apresentação do seu negócio' },
    ],
  },
  'inteligencia-desenvolvimento-pessoal': {
    emoji: '🌱',
    title: 'Projeto Final: Meu Plano de Evolução',
    subtitle: 'Você aprendeu sobre si mesmo. Agora é hora de traçar seu caminho!',
    showProfitCalc: false,
    submitLabel: 'Concluir curso e gerar certificado 🎓',
    fields: [
      { db: 'business_name', label: 'Um objetivo pessoal que você quer alcançar', type: 'text', placeholder: 'Ex: Ficar mais confiante para falar em público' },
      { db: 'product_service', label: 'O que você já sabe fazer bem hoje', type: 'textarea', placeholder: 'Seus pontos fortes' },
      { db: 'problem_solved', label: 'O que você quer melhorar', type: 'textarea', placeholder: 'Seus pontos a desenvolver' },
      { db: 'marketing_strategy', label: 'Pequenas ações para chegar lá', type: 'textarea', placeholder: 'O que você vai fazer, passo a passo?' },
      { db: 'service_approach', label: 'Como você vai acompanhar sua evolução', type: 'textarea', placeholder: 'Como você vai saber se está progredindo?' },
      { db: 'social_post_text', label: 'Uma frase de compromisso com você mesmo(a)', type: 'textarea', placeholder: 'Escreva uma frase motivacional para o futuro' },
    ],
  },
  'informatica-do-zero': {
    emoji: '🖥️',
    title: 'Projeto Final: Meu Primeiro Documento Digital',
    subtitle: 'Você aprendeu o básico da informática. Agora é hora de criar!',
    showProfitCalc: false,
    submitLabel: 'Concluir curso e gerar certificado 🎓',
    fields: [
      { db: 'business_name', label: 'Título do seu documento', type: 'text', placeholder: 'Ex: Meu animal favorito' },
      { db: 'product_service', label: 'Parágrafo principal do documento', type: 'textarea', placeholder: 'Escreva o conteúdo principal' },
      { db: 'problem_solved', label: 'Por que você escolheu esse tema', type: 'textarea', placeholder: 'O que te interessa nesse assunto?' },
      { db: 'marketing_strategy', label: 'Título da sua apresentação (slides)', type: 'text', placeholder: 'Um título curto para os slides' },
      { db: 'service_approach', label: '3 pontos principais da apresentação', type: 'textarea', placeholder: 'Liste os pontos que você colocaria em cada slide' },
      { db: 'social_post_text', label: 'Frase de conclusão', type: 'textarea', placeholder: 'Como você fecharia sua apresentação?' },
    ],
  },
  'seguranca-na-internet': {
    emoji: '🔐',
    title: 'Projeto Final: Meu Manual de Segurança Digital',
    subtitle: 'Você aprendeu a se proteger. Agora é hora de registrar suas próprias regras!',
    showProfitCalc: false,
    submitLabel: 'Concluir curso e gerar certificado 🎓',
    fields: [
      { db: 'business_name', label: 'Título do meu manual', type: 'text', placeholder: 'Ex: Guia de Segurança da Ana' },
      { db: 'product_service', label: '3 regras de senha segura que vou seguir', type: 'textarea', placeholder: 'Liste suas regras pessoais' },
      { db: 'problem_solved', label: 'O que eu faço se um desconhecido tentar falar comigo', type: 'textarea', placeholder: 'Escreva seu plano de ação' },
      { db: 'marketing_strategy', label: 'O que eu nunca vou compartilhar online', type: 'textarea', placeholder: 'Liste informações que você vai proteger' },
      { db: 'service_approach', label: 'Como vou agir se ver cyberbullying', type: 'textarea', placeholder: 'Descreva sua atitude' },
      { db: 'social_post_text', label: 'Meu compromisso de segurança digital', type: 'textarea', placeholder: 'Escreva uma frase de compromisso' },
    ],
  },
  'inteligencia-artificial-para-criancas': {
    emoji: '🤖',
    title: 'Projeto Final: Meu Primeiro Projeto com IA',
    subtitle: 'Você aprendeu a usar IA com criatividade e responsabilidade. Hora de criar algo!',
    showProfitCalc: false,
    submitLabel: 'Concluir curso e gerar certificado 🎓',
    fields: [
      { db: 'business_name', label: 'Nome do meu projeto com IA', type: 'text', placeholder: 'Ex: Minha história do dragão medroso' },
      { db: 'product_service', label: 'O que eu pedi para a IA me ajudar a criar', type: 'textarea', placeholder: 'Descreva o que você pediu, com ajuda de um responsável' },
      { db: 'problem_solved', label: 'Como eu verifiquei se a informação estava correta', type: 'textarea', placeholder: 'Que fontes você usou para checar?' },
      { db: 'marketing_strategy', label: 'O que a IA fez bem nesse projeto', type: 'textarea', placeholder: 'O que funcionou?' },
      { db: 'service_approach', label: 'O que eu mudaria ou melhoraria', type: 'textarea', placeholder: 'O que você ajustou com suas próprias ideias?' },
      { db: 'social_post_text', label: 'Uma coisa que aprendi sobre usar IA com responsabilidade', type: 'textarea', placeholder: 'Escreva sua reflexão final' },
    ],
  },
  'programacao-para-criancas': {
    emoji: '🎮',
    title: 'Projeto Final: Meu Primeiro Jogo',
    subtitle: 'Você aprendeu lógica de programação. Agora é hora de planejar seu próprio jogo!',
    showProfitCalc: false,
    submitLabel: 'Concluir curso e gerar certificado 🎓',
    fields: [
      { db: 'business_name', label: 'Nome do meu jogo', type: 'text', placeholder: 'Ex: Caça-Estrelas' },
      { db: 'product_service', label: 'Objetivo do jogador', type: 'textarea', placeholder: 'O que o jogador precisa fazer para vencer?' },
      { db: 'problem_solved', label: 'Regras principais (o que faz ganhar ou perder)', type: 'textarea', placeholder: 'Descreva as condições de vitória e derrota' },
      { db: 'marketing_strategy', label: 'Que eventos ou ações o jogador pode fazer', type: 'textarea', placeholder: 'Ex: apertar uma tecla para pular' },
      { db: 'service_approach', label: 'Que variáveis o jogo precisa guardar', type: 'textarea', placeholder: 'Ex: pontos, vidas, tempo' },
      { db: 'social_post_text', label: 'O que mais gostei de planejar nesse jogo', type: 'textarea', placeholder: 'Escreva sua reflexão final' },
    ],
  },
}

export const DEFAULT_TEMPLATE = PROJECT_TEMPLATES['educacao-financeira-empreendedorismo']
